"use client";

import { useState } from "react";
import { Skull, Loader2, Download, RotateCcw } from "lucide-react";

interface GauntletResult {
  clarityCheck: {
    oneLiner: string;
    problem: string;
    solution: string;
    score: number;
  };
  killShots: string[];
  marketReality: {
    existingAlternatives: string[];
    whoPaysTodayFor: string;
    marketSize: string;
    difficulty: string;
  };
  yourEdge: {
    whyYou: string;
    whyNow: string;
    unfairAdvantage: string;
    moatPotential: string;
  };
  verdict: {
    decision: "GO" | "PAUSE" | "KILL";
    confidence: number;
    reasoning: string;
    nextSteps: string[];
  };
}

export default function IdeaGauntletPage() {
  const [idea, setIdea] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<GauntletResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const runGauntlet = async () => {
    if (!idea.trim()) return;
    
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch("/api/tools/idea-gauntlet", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ idea }),
      });

      if (!response.ok) {
        throw new Error("Failed to run gauntlet");
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const exportMarkdown = () => {
    if (!result) return;
    
    const md = `# Idea Gauntlet Results

## The Idea
${idea}

---

## 1. Clarity Check (Score: ${result.clarityCheck.score}/10)

**One-liner:** ${result.clarityCheck.oneLiner}

**Problem:** ${result.clarityCheck.problem}

**Solution:** ${result.clarityCheck.solution}

---

## 2. Kill Shots 💀

${result.killShots.map((shot, i) => `${i + 1}. ${shot}`).join("\n")}

---

## 3. Market Reality

**Who pays for this today?** ${result.marketReality.whoPaysTodayFor}

**Existing alternatives:**
${result.marketReality.existingAlternatives.map(alt => `- ${alt}`).join("\n")}

**Market size:** ${result.marketReality.marketSize}

**Difficulty:** ${result.marketReality.difficulty}

---

## 4. Your Edge

**Why you?** ${result.yourEdge.whyYou}

**Why now?** ${result.yourEdge.whyNow}

**Unfair advantage:** ${result.yourEdge.unfairAdvantage}

**Moat potential:** ${result.yourEdge.moatPotential}

---

## 5. Verdict: ${result.verdict.decision}

**Confidence:** ${result.verdict.confidence}%

**Reasoning:** ${result.verdict.reasoning}

**Next steps:**
${result.verdict.nextSteps.map(step => `- ${step}`).join("\n")}

---
*Generated by Idea Gauntlet*
`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "idea-gauntlet-results.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setIdea("");
    setResult(null);
    setError(null);
  };

  const verdictColors = {
    GO: "text-green-400 bg-green-400/10 border-green-400/30",
    PAUSE: "text-yellow-400 bg-yellow-400/10 border-yellow-400/30",
    KILL: "text-red-400 bg-red-400/10 border-red-400/30",
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Skull className="w-8 h-8 text-red-400" />
          <h1 className="text-3xl font-bold">Idea Gauntlet</h1>
        </div>
        <p className="text-[var(--text-secondary)]">
          Stress test your idea. No sugarcoating. Either it survives or it dies.
        </p>
      </div>

      {!result ? (
        <div className="space-y-6">
          <div>
            <label className="block text-sm text-[var(--text-tertiary)] mb-2">
              Describe your idea in 2-3 sentences
            </label>
            <textarea
              value={idea}
              onChange={(e) => setIdea(e.target.value)}
              placeholder="e.g., A subscription service that sends personalized vitamin packs based on your health data and goals..."
              className="w-full h-40 px-4 py-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg text-[var(--text-primary)] placeholder:text-[var(--text-quaternary)] focus:outline-none focus:border-[var(--accent)] resize-none"
            />
          </div>

          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400">
              {error}
            </div>
          )}

          <button
            onClick={runGauntlet}
            disabled={!idea.trim() || loading}
            className="flex items-center gap-2 px-6 py-3 bg-[var(--accent)] text-[var(--bg-base)] rounded-lg font-medium hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Running Gauntlet...
              </>
            ) : (
              <>
                <Skull className="w-5 h-5" />
                Run the Gauntlet
              </>
            )}
          </button>
        </div>
      ) : (
        <div className="space-y-8">
          {/* Original idea */}
          <div className="p-4 bg-[var(--bg-elevated)] rounded-lg border border-[var(--border-subtle)]">
            <div className="text-xs text-[var(--text-quaternary)] uppercase tracking-wider mb-2">Your Idea</div>
            <p className="text-[var(--text-secondary)]">{idea}</p>
          </div>

          {/* Clarity Check */}
          <Section title="1. Clarity Check" score={result.clarityCheck.score}>
            <div className="space-y-4">
              <Field label="One-liner" value={result.clarityCheck.oneLiner} />
              <Field label="Problem" value={result.clarityCheck.problem} />
              <Field label="Solution" value={result.clarityCheck.solution} />
            </div>
          </Section>

          {/* Kill Shots */}
          <Section title="2. Kill Shots" icon="💀">
            <ol className="list-decimal list-inside space-y-2">
              {result.killShots.map((shot, i) => (
                <li key={i} className="text-[var(--text-secondary)]">{shot}</li>
              ))}
            </ol>
          </Section>

          {/* Market Reality */}
          <Section title="3. Market Reality">
            <div className="space-y-4">
              <Field label="Who pays for this today?" value={result.marketReality.whoPaysTodayFor} />
              <div>
                <div className="text-xs text-[var(--text-quaternary)] uppercase tracking-wider mb-2">Existing Alternatives</div>
                <ul className="list-disc list-inside space-y-1">
                  {result.marketReality.existingAlternatives.map((alt, i) => (
                    <li key={i} className="text-[var(--text-secondary)]">{alt}</li>
                  ))}
                </ul>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <Field label="Market Size" value={result.marketReality.marketSize} />
                <Field label="Difficulty" value={result.marketReality.difficulty} />
              </div>
            </div>
          </Section>

          {/* Your Edge */}
          <Section title="4. Your Edge">
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <Field label="Why you?" value={result.yourEdge.whyYou} />
                <Field label="Why now?" value={result.yourEdge.whyNow} />
              </div>
              <Field label="Unfair advantage" value={result.yourEdge.unfairAdvantage} />
              <Field label="Moat potential" value={result.yourEdge.moatPotential} />
            </div>
          </Section>

          {/* Verdict */}
          <div className={`p-6 rounded-lg border ${verdictColors[result.verdict.decision]}`}>
            <div className="flex items-center justify-between mb-4">
              <div className="text-2xl font-bold">{result.verdict.decision}</div>
              <div className="text-sm opacity-80">{result.verdict.confidence}% confidence</div>
            </div>
            <p className="mb-4">{result.verdict.reasoning}</p>
            <div>
              <div className="text-xs uppercase tracking-wider mb-2 opacity-60">Next Steps</div>
              <ul className="list-disc list-inside space-y-1">
                {result.verdict.nextSteps.map((step, i) => (
                  <li key={i}>{step}</li>
                ))}
              </ul>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-4">
            <button
              onClick={exportMarkdown}
              className="flex items-center gap-2 px-4 py-2 bg-[var(--bg-hover)] text-[var(--text-secondary)] rounded-lg hover:bg-[var(--bg-elevated)] transition-colors"
            >
              <Download className="w-4 h-4" />
              Export Markdown
            </button>
            <button
              onClick={reset}
              className="flex items-center gap-2 px-4 py-2 bg-[var(--bg-hover)] text-[var(--text-secondary)] rounded-lg hover:bg-[var(--bg-elevated)] transition-colors"
            >
              <RotateCcw className="w-4 h-4" />
              Test Another Idea
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function Section({ title, children, score, icon }: { title: string; children: React.ReactNode; score?: number; icon?: string }) {
  return (
    <div className="p-6 bg-[var(--bg-elevated)] rounded-lg border border-[var(--border-subtle)]">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold flex items-center gap-2">
          {title} {icon && <span>{icon}</span>}
        </h2>
        {score !== undefined && (
          <div className="text-sm text-[var(--text-tertiary)]">Score: {score}/10</div>
        )}
      </div>
      {children}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-[var(--text-quaternary)] uppercase tracking-wider mb-1">{label}</div>
      <p className="text-[var(--text-secondary)]">{value}</p>
    </div>
  );
}
